-- require('copilot').setup({
-- 	panel = {
-- 		enabled = false,
-- 		auto_refresh = false,
-- 		keymap = {
-- 			jump_prev = "[[",
-- 			jump_next = "]]",
-- 			accept = "<C-x><C-z>",
-- 			refresh = "gr",
-- 			open = "<M-CR>"
-- 		},
-- 		layout = {
-- 			position = "bottom",
-- 			ratio = 0.4
-- 		},
-- 	},
-- 	suggestion = {
-- 		enabled = false,
-- 		auto_trigger = false,
-- 		debounce = 75,
-- 		keymap = {
-- 			accept = "<C-f>",
-- 			accept_word = false,
-- 			accept_line = false,
-- 			next = "<M-\\>",
-- 			prev = "<M-[>",
-- 			dismiss = "<C-]>",
-- 		},
-- 	},
-- 	filetypes = {
-- 		yaml = false,
-- 		markdown = false,
-- 		help = false,
-- 		gitcommit = false,
-- 		gitrebase = false,
-- 		hgcommit = false,
-- 		svn = false,
-- 		cvs = false,
-- 		["."] = false,
-- 	},
-- 	copilot_node_command = 'node',
-- 	server_opts_overrides = {},
-- })

-- vim.api.nvim_set_keymap('n', '<leader>g', ':Copilot enable<CR>', { noremap = true, silent = true })
-- vim.api.nvim_set_keymap('n', '<leader>G', ':Copilot disable<CR>', { noremap = true, silent = true })
